### ISSUE TITLE
Exploiting receivers for APIs

### ISSUE THREAD

**Issue by ennioVisco** [typesafegithub/github-workflows-kt#874]
**What feature do you need?**
I believe it could be cool to adopt the now stable [Function Literals with Receivers](https://kotlinlang.org/docs/lambdas.html#function-literals-with-receiver) of Kotlin for new simpler APIs

**Previous API**

```kt
#!/usr/bin/env kotlin

@file:DependsOn("io.github.typesafegithub:github-workflows-kt:0.45.0")

import io.github.typesafegithub.workflows.actions.actions.CheckoutV3
import io.github.typesafegithub.workflows.domain.RunnerType.UbuntuLatest
import io.github.typesafegithub.workflows.domain.triggers.Push
import io.github.typesafegithub.workflows.dsl.workflow
import io.github.typesafegithub.workflows.yaml.toYaml

val workflow = workflow(
    name = "Test workflow",
    on = listOf(Push()),
    sourceFile = __FILE__.toPath(),
) {
    job(id = "test_job", runsOn = UbuntuLatest) {
        uses(name = "Check out", action = CheckoutV3())
        run(name = "Print greeting", command = "echo 'Hello world!'")
    }
}

workflow.writeToFile()
```

**New API**
```kt
#!/usr/bin/env kotlin

@file:DependsOn("io.github.typesafegithub:github-workflows-kt:0.45.0")

import io.github.typesafegithub.workflows.actions.actions.CheckoutV3
import io.github.typesafegithub.workflows.domain.RunnerType.UbuntuLatest
import io.github.typesafegithub.workflows.domain.triggers.Push
import io.github.typesafegithub.workflows.dsl.workflow
import io.github.typesafegithub.workflows.yaml.toYaml

workflow {
    name = "Test workflow"
    on = listOf(Push())
    sourceFile = __FILE__.toPath()

    job {
       id = "test_job"
       runsOn = UbuntuLatest
       uses(name = "Check out", action = CheckoutV3())
       run {
           name = "Print greeting"
           command = "echo 'Hello world!'"
       }
    }

    writeToFile()
}
```

**Implementation sketch**
The idea is to re-implement the `workflow`, `job` and `run` functions following this idea:
```kt
fun workflow(details: WorkflowBuilder.() -> Unit): String {
    return details(this)
}
```

I hope this sketch delivers the idea... 

**Key advantages**
- It more closely maps the Yaml syntax, without losing any of the type-safety and IDE's tooling
- It's an API more similar to Gradle's when you do things like:
<img width="575" alt="image" src="https://github.com/typesafegithub/github-workflows-kt/assets/740025/69ecedef-da61-4642-859f-f80b8da26cd2">

*** Updates ***

- 14/06: Changed from `toYaml()` to `writeToFile()`

**Comment by krzema12** [comment]
That's an interesting idea! But it also made me realize that the ["getting started" guide](https://typesafegithub.github.io/github-workflows-kt/user-guide/getting_started/) shows the approach with

```kotlin
val workflow = workflow { ... }
println(workflow.toYaml())
```

and I'd actually recommend (and I use it in my workflows, see e.g [here](https://github.com/typesafegithub/github-workflows-kt/blob/075a950e8d948b96047187d99722d3f0972cfae0/.github/workflows/build.main.kts)):

```kotlin
workflow { ...
}.writeToFile()
```

which is a bit nicer because there's no raw `println`.

I like the `writeToFile()` approach because we're explicit about the IO - when it happens and **that** it happens, and I'm afraid if we hide it in the workflow builder, it would be harder to implement scenarios when people want to have more control over when the YAML file is written.

Let me think about it, and also feel free to start a discussion on Kotlin's Slack (#github-workflows-kt) to gather feedback. We're just before publishing a stable v1.0 version and this looks like a breaking change, so it's good to clarify it sooner than later.

I'll also update the docs to point to the `writeToFile()` approach.

**Comment by krzema12** [comment]
https://github.com/typesafegithub/github-workflows-kt/pull/875

**Comment by ennioVisco** [comment]
> That's an interesting idea! But it also made me realize that the ["getting started" guide](https://typesafegithub.github.io/github-workflows-kt/user-guide/getting_started/) shows the approach with
> 
> ```kotlin
> val workflow = workflow { ... }
> println(workflow.toYaml())
> ```
> 
> and I'd actually recommend (and I use it in my workflows, see e.g [here](https://github.com/typesafegithub/github-workflows-kt/blob/075a950e8d948b96047187d99722d3f0972cfae0/.github/workflows/build.main.kts)):
> 
> ```kotlin
> workflow { ...
> }.writeToFile()
> ```
> 
> which is a bit nicer because there's no raw `println`.
> 
> I like the `writeToFile()` approach because we're explicit about the IO - when it happens and **that** it happens, and I'm afraid if we hide it in the workflow builder, it would be harder to implement scenarios when people want to have more control over when the YAML file is written.
> 
> Let me think about it, and also feel free to start a discussion on Kotlin's Slack (#github-workflows-kt) to gather feedback. We're just before publishing a stable v1.0 version and this looks like a breaking change, so it's good to clarify it sooner than later.
> 
> I'll also update the docs to point to the `writeToFile()` approach.

I figured this would be a very big change... I'd love to chat about it but it seems I cannot access it, can you maybe invite me? 

About the `writeToFile()` I'm not entirely convinced it should be part of the spec: 
I guess a fair point is that ideally the spec-file should be usable whether it is passed as an object, or written to a file. 
Nevertheless I would provide same __reasonable default__ to allow a gradual usage of the capabilities of the library (for simple scripts it might make sense not to control the output.

**Comment by krzema12** [comment]
Some discussion happened in this thread: https://kotlinlang.slack.com/archives/C02UUATR7RC/p1686745506417979, along with covering some side topics.

To summarize, we agreed to leave the API as is for now because it's impossible to ensure that a given property was set in compile time. @ennioVisco could you revisit this request and let me know what is your current proposal?

**Comment by krzema12** [comment]
I'm going to resolve for now, but feel free to reopen if there's more clarity around the proposal.

**Comment by ennioVisco** [comment]
> I'm going to resolve for now, but feel free to reopen if there's more clarity around the proposal.



> Some discussion happened in this thread: https://kotlinlang.slack.com/archives/C02UUATR7RC/p1686745506417979, along with covering some side topics.
> 
> To summarize, we agreed to leave the API as is for now because it's impossible to ensure that a given property was set in compile time. @ennioVisco could you revisit this request and let me know what is your current proposal?

Sorry, I was on vacation and missed a few notifications. 
I think overall the discussion on slack was very nice and insightful. 
I believe what makes the most sense is to follow the suggestion to go on with v1 as it is now, and maybe consider this change in a future version, when kotlin script gets the attention and updates it deserves!
